data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/user_data/houq/transformer_share/cwmt2018_zh2en/train.seg"
    - "/home/user_data/houq/transformer_share/cwmt2018_zh2en/train.target"
    - "/home/user_data/houq/transformer_share/cwmt2018_zh2en/train.hter"
  valid_data:
    - "/home/user_data/houq/transformer_share/cwmt2018_zh2en/dev.seg"
    - "/home/user_data/houq/transformer_share/cwmt2018_zh2en/dev.target"
    - "/home/user_data/houq/transformer_share/cwmt2018_zh2en/dev.hter"
  vocabularies:
    - type: "word"
      dict_path: "/home/user_data/weihr/NMT_DATA_PY3/NIST-ZH-EN/vocab/zh.json"
      max_n_words: 30000
    - type: "word"
      dict_path: "/home/user_data/weihr/NMT_DATA_PY3/NIST-ZH-EN/vocab/en.json"
      max_n_words: 30000
  max_len:
    - 80
    - 80

transformer_model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 512
  d_model: 512
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.1

model_configs:
  model: QE
  feature_size: 2052
  hidden_size: 512
  label_smoothing: 0
  dropout: 0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.001
  grad_clip: 1.0
  optimizer_params: ~
  schedule_method: ~
  scheduler_configs:
    patience: 2
    min_lr: 0.00005
    scale: 0.5

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: false
  use_bucket: false
  batch_size: 1000
  batching_key: "samples"
  update_cycle: 1
  valid_batch_size: 50
  disp_freq: 10
  save_freq: 100
  num_kept_checkpoints: 1
  loss_valid_freq: 100
  bleu_valid_freq: 1000
  bleu_valid_batch_size: 5
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 150
    beam_size: 5
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 50